### ISSUE TITLE
Includes-what-you-use not works in VS 2022

### ISSUE THREAD

**Issue by mark5231** [Agrael1/IncludeToolbox#11]
```C++
#include <iostream>
#include <vector>

int main()
{
	std::cout << "Hello World!\n";
}
```
Even for this simple file, Includes-what-you-use still cannot delete the vector header. 

I use the default setting, right-click on the cpp file and click `Run Include-What-You-Use`.  
The result is it only formats my code, the header is still there.

**Comment by mark5231** [comment]
<img width="715" alt="image" src="https://user-images.githubusercontent.com/91494227/207473684-352dd227-7d56-4c9b-9ce6-355ce8d53bb8.png">

**Comment by Agrael1** [comment]
What does the output window say? I launched the IWYU on the clear VS2022 without any predefined parameters, it works fine.

**Comment by mark5231** [comment]
Hi Agrael1. Thanks for your reply. This bug is hard to hit, I opened another ConsoleApplication, this time Include-What-You-Use can delete the <vector> header. And when Include-What-You-Use fails, there is nothing in the output window.

**Comment by mark5231** [comment]
Another thing is, there is only Include-What-You-Use in my right-click menu. I don't have Include Formatter and Trial and Error Include Removal. Is this a bug? Is there a way to debug this extension? So, maybe I can fix it.

**Comment by Agrael1** [comment]
> Another thing is, there is only Include-What-You-Use in my right-click menu. I don't have Include Formatter and Trial and Error Include Removal. Is this a bug? Is there a way to debug this extension? So, maybe I can fix it.

the format and other options are in code window, you need to right click anywhere on the code. For the format you need to select headers you wish to format, and right click in the selection
