### ISSUE TITLE
Publishing to Open VSX Registry (for VSCodium, etc.)

### ISSUE THREAD

**Issue by Dominik-K** [Agrael1/IncludeToolbox#20]
Hi,

your extension looks good. :+1: 

Would you mind to publish it also to the [Open VSX Registry](https://open-vsx.org)? Then it can also easily be added as extension in [VSCodium](https://vscodium.com/), [Ecplise Theia](http://theia-ide.org/) and other free IDEs (see this [Eclipse newsletter](https://www.eclipse.org/community/eclipse_newsletter/2020/march/1.php)).

Thanks.

**Comment by Agrael1** [comment]
Hello, @Dominik-K, the extension is for Visual Studio. Does it work for VSCode or exlipse out of the box?

**Comment by Dominik-K** [comment]
Oh, right. Damn, I've overseen this. Sorry.
